apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rag-backend
  name: rag-backend
  namespace: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: rag-backend
    spec:
      containers:
        - image: 869935100386.dkr.ecr.us-east-1.amazonaws.com/backend:rag_backend_2
          name: backend
          resources: {}
          volumeMounts:
            - name: backend-config-volume
              mountPath: /app
      volumes:
        - name: backend-config-volume
          configMap:
            name: backend-config
status: {}
