apiVersion: v1
kind: Service
metadata:
  name: backend-rag-lb 
  namespace: rag
spec:
  selector:
    app: rag-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002