apiVersion: v1
kind: Service
metadata:
  name: chromadb
  labels:
    app: chromadb
spec:
  ports:
    - port: 8000
      name: http
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: chromadb
