apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chromadb
  namespace: rag
spec:
  selector:
    matchLabels:
      app: chromadb
  serviceName: "chromadb"
  replicas: 1
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
        - name: chromadb
          image: 869935100386.dkr.ecr.us-east-1.amazonaws.com/backend:rag_db  # Or your preferred tag
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: chromadb-storage
              mountPath: /chroma/chroma  # default data path for ChromaDB
          env:
            - name: IS_PERSISTENT
              value: "true"
      volumes:
        - name: chromadb-storage
          persistentVolumeClaim:
            claimName: rag-pvc
