apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chromadb
spec:
  selector:
    matchLabels:
      app: chromadb
  serviceName: "chromadb"
  replicas: 1
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
        - name: chromadb
          image: chromadb/chromadb:latest  # Or your preferred tag
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: chromadb-storage
              mountPath: /chroma/chroma  # default data path for ChromaDB
          env:
            - name: IS_PERSISTENT
              value: "true"
  volumeClaimTemplates:
    - metadata:
        name: chromadb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi